import type { Metadata } from 'next'
import { Quicksand } from "next/font/google"
import './globals.css'
const mainFont = Quicksand ({
  subsets: ["latin"]
})
export const metadata: Metadata = {
  title: 'Taylor Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={mainFont.className}>
        <div className='flex mt-[3rem] justify-center'>{children}</div>
        </body>
    </html>
  )
}
